apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
        values:
          targetRevision: main
    - clusters:
        selector:
          matchLabels:
            environment: prd
        values:
          targetRevision: main
  template:
    metadata:
      name: 'argocd'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      source:
        repoURL: https://github.com/maartenkamoen/edge-dev-argocd-example.git
        targetRevision: '{{values.targetRevision}}'
        path: talos/add-ons/argocd
      destination:
        server: '{{server}}'
        namespace: 'argocd'
