---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-helm
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
        values:
          targetRevision: 1.17.1
    - clusters:
        selector:
          matchLabels:
            environment: acc
        values:
          targetRevision: 1.17.1
    - clusters:
        selector:
          matchLabels:
            environment: prd
        values:
          targetRevision: 1.17.0
  template:
    metadata:
      name: 'cert-manager'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      source:
        chart: cert-manager
        repoURL: https://charts.jetstack.io
        targetRevision: '{{values.targetRevision}}'
        helm:
          releaseName: cert-manager
          valuesObject:
            crds:
              enabled: true
              keep: true
      destination:
        server: '{{server}}'
        namespace: cert-manager
