---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-vip
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
        values:
          targetRevision: v0.6.6
    - clusters:
        selector:
          matchLabels:
            environment: prd
        values:
          targetRevision: v0.6.6
  template:
    metadata:
      name: 'kube-vip'
    spec:
      project: default
      source:
        chart: kube-vip
        repoURL: https://kube-vip.github.io/helm-charts
        targetRevision: '{{values.targetRevision}}'
        helm:
          releaseName: kube-vip
          values: |
            env:
              vip_interface: "ens6"
              vip_arp: "true"
              lb_enable: "false"
              cp_enable: "false"
              svc_enable: "true"
              vip_leaderelection: "true"
              svc_election: "true"
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-vip-cloud-provider
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
        values:
          targetRevision: v0.2.5
    - clusters:
        selector:
          matchLabels:
            environment: prd
        values:
          targetRevision: v0.2.5
  template:
    metadata:
      name: 'kube-vip-cloud-provider'
    spec:
      project: default
      source:
        chart: kube-vip-cloud-provider
        repoURL: https://kube-vip.github.io/helm-charts
        targetRevision: '{{values.targetRevision}}'
        helm:
          releaseName: kube-vip-cloud-provider
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-vip-configmap
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
            site: nijmegen01
        values:
          addresspool: 192.168.122.100-192.168.122.109
    - clusters:
        selector:
          matchLabels:
            environment: tst
            site: nijmegen02
        values:
          addresspool: 192.168.122.110-192.168.122.119
    - clusters:
        selector:
          matchLabels:
            environment: prd
            site: nijmegen01
        values:
          addresspool: 192.168.122.120-192.168.122.129
  template:
    metadata:
      name: 'kube-vip-configmap'
    spec:
      project: default
      source:
        repoURL: https://github.com/maartenkamoen/edge-dev-argocd-example.git
        targetRevision: HEAD
        path: talos/add-ons/kube-vip-configmap
        helm:
          values: |
            addresspool: "{{values.addresspool}}"
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
