---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
        values:
          targetRevision: v0.14.9
    - clusters:
        selector:
          matchLabels:
            environment: prd
        values:
          targetRevision: v0.14.9
  template:
    metadata:
      name: 'metallb'
    spec:
      project: default
      sources:
        - chart: metallb
          repoURL: https://metallb.github.io/metallb
          targetRevision: '{{values.targetRevision}}'
          helm:
            releaseName: metallb
      destination:
        server: '{{server}}'
        namespace: metallb-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb-config
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: tst
            site: nijmegen01
        values:
          metallb_addresspool: 192.168.122.100-192.168.122.110
          metallb_interface: ens6
          metallb_pool_name: pool0
    - clusters:
        selector:
          matchLabels:
            environment: tst
            site: nijmegen02
        values:
          metallb_addresspool: 192.168.122.111-192.168.122.120
          metallb_interface: ens6
          metallb_pool_name: pool0
    - clusters:
        selector:
          matchLabels:
            environment: prd
            site: nijmegen01
        values:
          metallb_addresspool: 192.168.122.121-192.168.122.130
          metallb_interface: ens6
          metallb_pool_name: pool0
  template:
    metadata:
      name: 'metallb-config'
    spec:
      project: default
      source:
        repoURL: https://github.com/maartenkamoen/edge-dev-argocd-example.git
        targetRevision: HEAD
        path: talos/add-ons/metallb-config
        helm:
          values: |
            metallb_addresspool: "{{values.metallb_addresspool}}"
            metallb_interface: "{{values.metallb_interface}}"
            metallb_pool_name: "{{values.metallb_pool_name}}"
      destination:
        server: '{{server}}'
        namespace: metallb-system
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
