---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maartenkamoen/edge-dev-argocd-example.git
    targetRevision: main
    path: capi/add-ons/kubevirt
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
